
function ALU_Control_config(this_block)

  % Revision History:
  %
  %   14-Nov-2021  (20:02 hours):
  %     Original code was machine generated by Xilinx's System Generator after parsing
  %     C:\Users\the20\Desktop\ECTE432-Project-main\ALU_Control.vhd
  %
  %

  this_block.setTopLevelLanguage('VHDL');

  this_block.setEntityName('ALU_Control');

  % System Generator has to assume that your entity  has a combinational feed through; 
  %   if it  doesn't, then comment out the following line:
  this_block.tagAsCombinational;

  this_block.addSimulinkInport('Fnc');
  this_block.addSimulinkInport('ALUop');

  this_block.addSimulinkOutport('Operation');

  Operation_port = this_block.port('Operation');
  Operation_port.setType('UFix_4_0');

  % -----------------------------
  if (this_block.inputTypesKnown)
    % do input type checking, dynamic output type and generic setup in this code block.

    if (this_block.port('Fnc').width ~= 6);
      this_block.setError('Input data type for port "Fnc" must have width=6.');
    end

    if (this_block.port('ALUop').width ~= 2);
      this_block.setError('Input data type for port "ALUop" must have width=2.');
    end

  end  % if(inputTypesKnown)
  % -----------------------------

  % System Generator found no apparent clock signals in the HDL, assuming combinational logic.
  % -----------------------------
   if (this_block.inputRatesKnown)
     inputRates = this_block.inputRates; 
     uniqueInputRates = unique(inputRates); 
     outputRate = uniqueInputRates(1);
     for i = 2:length(uniqueInputRates)
       if (uniqueInputRates(i) ~= Inf)
         outputRate = gcd(outputRate,uniqueInputRates(i));
       end
     end  % for(i)
     for i = 1:this_block.numSimulinkOutports 
       this_block.outport(i).setRate(outputRate); 
     end  % for(i)
   end  % if(inputRatesKnown)
  % -----------------------------

    uniqueInputRates = unique(this_block.getInputRates);


  % Add addtional source files as needed.
  %  |-------------
  %  | Add files in the order in which they should be compiled.
  %  | If two files "a.vhd" and "b.vhd" contain the entities
  %  | entity_a and entity_b, and entity_a contains a
  %  | component of type entity_b, the correct sequence of
  %  | addFile() calls would be:
  %  |    this_block.addFile('b.vhd');
  %  |    this_block.addFile('a.vhd');
  %  |-------------

  %    this_block.addFile('');
  %    this_block.addFile('');
  this_block.addFile('ALU_Control.vhd');

return;


