
function Bit_Slicer_config(this_block)

  % Revision History:
  %
  %   14-Nov-2021  (15:00 hours):
  %     Original code was machine generated by Xilinx's System Generator after parsing
  %     C:\Users\the20\Desktop\ECTE432-Project-main\Bit_Slicer.vhd
  %
  %

  this_block.setTopLevelLanguage('VHDL');

  this_block.setEntityName('Bit_Slicer');

  % System Generator has to assume that your entity  has a combinational feed through; 
  %   if it  doesn't, then comment out the following line:
  this_block.tagAsCombinational;

  this_block.addSimulinkInport('instruction');

  this_block.addSimulinkOutport('opcode');
  this_block.addSimulinkOutport('RS');
  this_block.addSimulinkOutport('RT');
  this_block.addSimulinkOutport('RD');
  this_block.addSimulinkOutport('immediate');

  opcode_port = this_block.port('opcode');
  opcode_port.setType('UFix_6_0');
  RS_port = this_block.port('RS');
  RS_port.setType('UFix_5_0');
  RT_port = this_block.port('RT');
  RT_port.setType('UFix_5_0');
  RD_port = this_block.port('RD');
  RD_port.setType('UFix_5_0');
  immediate_port = this_block.port('immediate');
  immediate_port.setType('UFix_16_0');

  % -----------------------------
  if (this_block.inputTypesKnown)
    % do input type checking, dynamic output type and generic setup in this code block.

    if (this_block.port('instruction').width ~= 32);
      this_block.setError('Input data type for port "instruction" must have width=32.');
    end

  end  % if(inputTypesKnown)
  % -----------------------------

  % System Generator found no apparent clock signals in the HDL, assuming combinational logic.
  % -----------------------------
   if (this_block.inputRatesKnown)
     inputRates = this_block.inputRates; 
     uniqueInputRates = unique(inputRates); 
     outputRate = uniqueInputRates(1);
     for i = 2:length(uniqueInputRates)
       if (uniqueInputRates(i) ~= Inf)
         outputRate = gcd(outputRate,uniqueInputRates(i));
       end
     end  % for(i)
     for i = 1:this_block.numSimulinkOutports 
       this_block.outport(i).setRate(outputRate); 
     end  % for(i)
   end  % if(inputRatesKnown)
  % -----------------------------

    uniqueInputRates = unique(this_block.getInputRates);


  % Add addtional source files as needed.
  %  |-------------
  %  | Add files in the order in which they should be compiled.
  %  | If two files "a.vhd" and "b.vhd" contain the entities
  %  | entity_a and entity_b, and entity_a contains a
  %  | component of type entity_b, the correct sequence of
  %  | addFile() calls would be:
  %  |    this_block.addFile('b.vhd');
  %  |    this_block.addFile('a.vhd');
  %  |-------------

  %    this_block.addFile('');
  %    this_block.addFile('');
  this_block.addFile('Bit_Slicer.vhd');

return;


