
function Branch_Stall_config(this_block)

  % Revision History:
  %
  %   08-Dec-2021  (19:22 hours):
  %     Original code was machine generated by Xilinx's System Generator after parsing
  %     D:\Daily life\UOW\Fourth Year\ECTE432\ECTE432-Project\Branch_Stall.vhd
  %
  %

  this_block.setTopLevelLanguage('VHDL');

  this_block.setEntityName('Branch_Stall');

  % System Generator has to assume that your entity  has a combinational feed through; 
  %   if it  doesn't, then comment out the following line:
  this_block.tagAsCombinational;

  this_block.addSimulinkInport('Branch');

  this_block.addSimulinkOutport('PCSTALL');
  this_block.addSimulinkOutport('reset');

  PCSTALL_port = this_block.port('PCSTALL');
  PCSTALL_port.setType('UFix_1_0');
  PCSTALL_port.useHDLVector(false);
  reset_port = this_block.port('reset');
  reset_port.setType('UFix_1_0');
  reset_port.useHDLVector(false);

  % -----------------------------
  if (this_block.inputTypesKnown)
    % do input type checking, dynamic output type and generic setup in this code block.

    if (this_block.port('Branch').width ~= 1);
      this_block.setError('Input data type for port "Branch" must have width=1.');
    end

    this_block.port('Branch').useHDLVector(false);

  end  % if(inputTypesKnown)
  % -----------------------------

  % System Generator found no apparent clock signals in the HDL, assuming combinational logic.
  % -----------------------------
   if (this_block.inputRatesKnown)
     inputRates = this_block.inputRates; 
     uniqueInputRates = unique(inputRates); 
     outputRate = uniqueInputRates(1);
     for i = 2:length(uniqueInputRates)
       if (uniqueInputRates(i) ~= Inf)
         outputRate = gcd(outputRate,uniqueInputRates(i));
       end
     end  % for(i)
     for i = 1:this_block.numSimulinkOutports 
       this_block.outport(i).setRate(outputRate); 
     end  % for(i)
   end  % if(inputRatesKnown)
  % -----------------------------

    uniqueInputRates = unique(this_block.getInputRates);


  % Add addtional source files as needed.
  %  |-------------
  %  | Add files in the order in which they should be compiled.
  %  | If two files "a.vhd" and "b.vhd" contain the entities
  %  | entity_a and entity_b, and entity_a contains a
  %  | component of type entity_b, the correct sequence of
  %  | addFile() calls would be:
  %  |    this_block.addFile('b.vhd');
  %  |    this_block.addFile('a.vhd');
  %  |-------------

  %    this_block.addFile('');
  %    this_block.addFile('');
  this_block.addFile('Branch_Stall.vhd');

return;


