
function Data_Memory_config(this_block)

  % Revision History:
  %
  %   09-Dec-2021  (11:27 hours):
  %     Original code was machine generated by Xilinx's System Generator after parsing
  %     D:\Daily life\UOW\Fourth Year\ECTE432\ECTE432-Project\Data_Memory.vhd
  %
  %

  this_block.setTopLevelLanguage('VHDL');

  this_block.setEntityName('Data_Memory');

  % System Generator has to assume that your entity  has a combinational feed through; 
  %   if it  doesn't, then comment out the following line:
  this_block.tagAsCombinational;

  this_block.addSimulinkInport('clk');
  this_block.addSimulinkInport('mem_access_addr');
  this_block.addSimulinkInport('mem_write_data');
  this_block.addSimulinkInport('mem_write_en');
  this_block.addSimulinkInport('mem_read');

  this_block.addSimulinkOutport('mem_read_data');

  mem_read_data_port = this_block.port('mem_read_data');
  mem_read_data_port.setType('UFix_32_0');

  % -----------------------------
  if (this_block.inputTypesKnown)
    % do input type checking, dynamic output type and generic setup in this code block.

    if (this_block.port('clk').width ~= 1);
      this_block.setError('Input data type for port "clk" must have width=1.');
    end

    this_block.port('clk').useHDLVector(false);

    if (this_block.port('mem_access_addr').width ~= 32);
      this_block.setError('Input data type for port "mem_access_addr" must have width=32.');
    end

    if (this_block.port('mem_write_data').width ~= 32);
      this_block.setError('Input data type for port "mem_write_data" must have width=32.');
    end

    if (this_block.port('mem_write_en').width ~= 1);
      this_block.setError('Input data type for port "mem_write_en" must have width=1.');
    end

    this_block.port('mem_write_en').useHDLVector(false);

    if (this_block.port('mem_read').width ~= 1);
      this_block.setError('Input data type for port "mem_read" must have width=1.');
    end

    this_block.port('mem_read').useHDLVector(false);

  end  % if(inputTypesKnown)
  % -----------------------------

  % System Generator found no apparent clock signals in the HDL, assuming combinational logic.
  % -----------------------------
   if (this_block.inputRatesKnown)
     inputRates = this_block.inputRates; 
     uniqueInputRates = unique(inputRates); 
     outputRate = uniqueInputRates(1);
     for i = 2:length(uniqueInputRates)
       if (uniqueInputRates(i) ~= Inf)
         outputRate = gcd(outputRate,uniqueInputRates(i));
       end
     end  % for(i)
     for i = 1:this_block.numSimulinkOutports 
       this_block.outport(i).setRate(outputRate); 
     end  % for(i)
   end  % if(inputRatesKnown)
  % -----------------------------

    uniqueInputRates = unique(this_block.getInputRates);


  % Add addtional source files as needed.
  %  |-------------
  %  | Add files in the order in which they should be compiled.
  %  | If two files "a.vhd" and "b.vhd" contain the entities
  %  | entity_a and entity_b, and entity_a contains a
  %  | component of type entity_b, the correct sequence of
  %  | addFile() calls would be:
  %  |    this_block.addFile('b.vhd');
  %  |    this_block.addFile('a.vhd');
  %  |-------------

  %    this_block.addFile('');
  %    this_block.addFile('');
  this_block.addFile('Data_Memory.vhd');

return;


