
function Forwarding_Unit_config(this_block)

  % Revision History:
  %
  %   08-Dec-2021  (19:09 hours):
  %     Original code was machine generated by Xilinx's System Generator after parsing
  %     D:\Daily life\UOW\Fourth Year\ECTE432\ECTE432-Project\Forwarding_Unit.vhd
  %
  %

  this_block.setTopLevelLanguage('VHDL');

  this_block.setEntityName('Forwarding_Unit');

  % System Generator has to assume that your entity  has a combinational feed through; 
  %   if it  doesn't, then comment out the following line:
  this_block.tagAsCombinational;

  this_block.addSimulinkInport('EX_MEM_Rd');
  this_block.addSimulinkInport('MEM_WB_Rd');
  this_block.addSimulinkInport('EX_MEM_RegWrite');
  this_block.addSimulinkInport('MEM_WB_RegWrite');
  this_block.addSimulinkInport('ID_EX_Rs');
  this_block.addSimulinkInport('ID_EX_Rt');

  this_block.addSimulinkOutport('forwardA');
  this_block.addSimulinkOutport('forwardB');

  forwardA_port = this_block.port('forwardA');
  forwardA_port.setType('UFix_2_0');
  forwardB_port = this_block.port('forwardB');
  forwardB_port.setType('UFix_2_0');

  % -----------------------------
  if (this_block.inputTypesKnown)
    % do input type checking, dynamic output type and generic setup in this code block.

    if (this_block.port('EX_MEM_Rd').width ~= 5);
      this_block.setError('Input data type for port "EX_MEM_Rd" must have width=5.');
    end

    if (this_block.port('MEM_WB_Rd').width ~= 5);
      this_block.setError('Input data type for port "MEM_WB_Rd" must have width=5.');
    end

    if (this_block.port('EX_MEM_RegWrite').width ~= 1);
      this_block.setError('Input data type for port "EX_MEM_RegWrite" must have width=1.');
    end

    this_block.port('EX_MEM_RegWrite').useHDLVector(false);

    if (this_block.port('MEM_WB_RegWrite').width ~= 1);
      this_block.setError('Input data type for port "MEM_WB_RegWrite" must have width=1.');
    end

    this_block.port('MEM_WB_RegWrite').useHDLVector(false);

    if (this_block.port('ID_EX_Rs').width ~= 5);
      this_block.setError('Input data type for port "ID_EX_Rs" must have width=5.');
    end

    if (this_block.port('ID_EX_Rt').width ~= 5);
      this_block.setError('Input data type for port "ID_EX_Rt" must have width=5.');
    end

  end  % if(inputTypesKnown)
  % -----------------------------

  % System Generator found no apparent clock signals in the HDL, assuming combinational logic.
  % -----------------------------
   if (this_block.inputRatesKnown)
     inputRates = this_block.inputRates; 
     uniqueInputRates = unique(inputRates); 
     outputRate = uniqueInputRates(1);
     for i = 2:length(uniqueInputRates)
       if (uniqueInputRates(i) ~= Inf)
         outputRate = gcd(outputRate,uniqueInputRates(i));
       end
     end  % for(i)
     for i = 1:this_block.numSimulinkOutports 
       this_block.outport(i).setRate(outputRate); 
     end  % for(i)
   end  % if(inputRatesKnown)
  % -----------------------------

    uniqueInputRates = unique(this_block.getInputRates);


  % Add addtional source files as needed.
  %  |-------------
  %  | Add files in the order in which they should be compiled.
  %  | If two files "a.vhd" and "b.vhd" contain the entities
  %  | entity_a and entity_b, and entity_a contains a
  %  | component of type entity_b, the correct sequence of
  %  | addFile() calls would be:
  %  |    this_block.addFile('b.vhd');
  %  |    this_block.addFile('a.vhd');
  %  |-------------

  %    this_block.addFile('');
  %    this_block.addFile('');
  this_block.addFile('Forwarding_Unit.vhd');

return;


